#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d a s d f g h j k l z

bspc config border_width         0
bspc config window_gap           50 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# autostart

sxhkd -c ~/.config/bspwm/sxhkdrc &
